import SectionTitle from "@/components/section-title";
import { Button } from "@/components/ui/button";
import { Form, FormControl, FormDescription, FormField, FormItem, FormLabel, FormMessage } from "@/components/ui/form";
import Link from "next/link";
import ContactForm from "./components/contact-form";
import { Metadata } from "next";


export const metadata: Metadata = {
    title: 'Contacts',
    description: "Generated by create next app",
};


export default function Contact() {
    return (
        <ContactForm />
    )
}
