import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { ThemeProvider } from "@/components/ui/theme-provider";
import Link from "next/link";
import { Button } from "@/components/ui/button";
import { Github, Instagram, Linkedin, Mail, Twitter } from "lucide-react";
import { ModeToggle } from "@/components/mode-toggle";
import { SheetMenu } from "@/components/sheet-menu";
import Image from "next/image";

const inter = Inter({ subsets: ["latin"] });

export const navItems = [
  { label: "Work", href: "/work" },
  { label: "Photography", href: "/photography" },
  { label: "Contact", href: "/contact" },
]

export const metadata: Metadata = {
  title: {
    template: "%s | leo",
    default: "leo",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja" suppressHydrationWarning>
      <body className={cn(inter.className, 'min-h-dvh')}>
        <ThemeProvider
              attribute="class"
              defaultTheme="dark"
              enableSystem
              disableTransitionOnChange
        >
        <header className="container h-16 flex items-center border-b justify-between text-primary">
          <h1 className="font-bold text-2xl">
            <Link href="/">
              <div className="flex">
                <Image src="/profile.webp" alt="profile" width={32} height={32} className="rounded-md"></Image>
                <span className="ml-2">leo</span>
              </div>
            </Link>
          </h1>
          <ul className="flex gap-1 lg:gap-3">
            {navItems.map((item) => (
              <li key={item.label} className="hidden sm:block">
                <Button variant="ghost" asChild>
                  <Link href={item.href}>{item.label}</Link>
                </Button>
                </li>
              ))}
              <ModeToggle />
              <li className="block sm:hidden">
                <SheetMenu/>
              </li>
          </ul>
        </header>

        <main>
          {children}
        </main>

        <footer className="container sticky top-full flex items-center justify-between border-t text-primary p-4">
            <p className="text-sm">&copy;2024 leo</p>
            <div className="flex flex-col items-center justify-center gap-3">
              <ul className="flex gap-3 items-center justify-center">
                <li><a href="mailto:rka147@sfu.ca " ><Mail color="#17aa41"></Mail></a></li>
                <li><a href="https://linkedin.com" target="_blank" rel="noopener noreferrer"><Linkedin color="#0077b5"></Linkedin></a></li>
                <li><a href="https://twitter.com" target="_blank" rel="noopener noreferrer"><Twitter color="#1da1f2"></Twitter></a></li>
                <li><a href="https://github.com" target="_blank" rel="noopener noreferrer"><Github ></Github></a></li>
                <li><a href="https://instagram.com/leok_can" target="_blank" rel="noopener noreferrer"><Instagram color="#e1306c"></Instagram></a></li>
              </ul>
            </div>
        </footer>

        </ThemeProvider>
        
      </body>
    </html>
  );
}
