import SectionTitle from "@/components/section-title";
import { Button } from "@/components/ui/button";
import Link from "next/link";
import { CarouselPhoto } from "./components/carousel-photo";
import { Metadata } from "next";
import PageTitle from "@/components/page-title";


export const metadata: Metadata = {
    title: 'About Services',
    description: "Generated by create next app",
};

export default function About() {
    return (
        <div>
            <PageTitle title="Photography">
                <p className="text-muted-foreground mb-6">
                    Photography is an art form that captures the world around me, preserving moments in time forever. Our service offers professional skills and creative perspectives to beautifully document your precious moments.
                </p>
                <Button>
                    <Link href="/contact">Contact</Link>
                </Button>
            </PageTitle>
            <div className="container py-14 items-center flex justify-center gap-5">
                <CarouselPhoto />
            </div>
        </div>

    )
}
