import SectionTitle from "@/components/section-title";
import { Button } from "@/components/ui/button";
import Link from "next/link";
import { CarouselPhoto } from "./components/carousel-photo";
import { Metadata } from "next";
import PageTitle from "@/components/page-title";


export const metadata: Metadata = {
    title: 'About Services',
    description: "Generated by create next app",
};

export default function About() {
    return (
        <div>
            <PageTitle title="Photography">
                <p className="text-muted-foreground mb-6">
                    Lorem ipsum dolor sit amet consectetur adipisicing elit. A, necessitatibus id. Minima, velit debitis quo aliquam quidem aspernatur, odit ipsum odio adipisci optio corporis modi nihil distinctio dignissimos eveniet est.
                </p>
                <Button>
                    <Link href="/contact">Contact</Link>
                </Button>
            </PageTitle>
            <div className="container py-14 items-center flex justify-center gap-5">
                <CarouselPhoto />
            </div>
        </div>

    )
}
